FROM arm64v8/python:3.10-slim

COPY docker-requirements-l4t.txt prebuilt/*.whl ./

# Install the python requirements
RUN python3 -m pip install pip==21.3.1 setuptools==59.6.0 wheel==0.37.1 && \
    python3 -m pip install -r docker-requirements-l4t.txt --find-links .

COPY custom_parameter_image_server.py /app/
WORKDIR /app

ENTRYPOINT ["python3", "/app/custom_parameter_image_server.py"]