FROM nvcr.io/nvidia/l4t-tensorflow:r35.3.1-tf2.11-py3

# Needed for OpenCV
RUN apt-get update && apt-get install ffmpeg libsm6 libxext6 -y python3-opencv

COPY docker-requirements_server.txt prebuilt/*.whl ./

# Install the python requirements
RUN python3 -m pip install pip==21.3.1 setuptools==59.6.0 wheel==0.37.1 && \
    python3 -m pip install -r docker-requirements_server.txt --find-links .

COPY tensorflow_server.py /app/
WORKDIR /app

ENTRYPOINT ["python3", "/app/tensorflow_server.py"]
